// Tüm kullanıcıya görünen metinler — tek kaynak. İngilizce varsayılan, Türkçe alternatif.
//
// Neden chrome.i18n değil: çekirdek modüller (otp/kripto/depo) Node'da test ediliyor,
// orada chrome nesnesi yok. Burası saf JS olduğu için hem tarayıcıda hem testte çalışır.
// chrome.i18n yalnızca manifest'teki ad/açıklama için kullanılır (_locales/).
//
// `$1`, `$2` yer tutucuları t() çağrısındaki sırayla değiştirilir.
"use strict";

export const METINLER = {
  en: {
    /* --- çekirdek hatalar --- */
    gizliBos: "The secret key is empty.",
    gizliKisa: "The secret key is too short.",
    base32Gecersiz: 'Invalid Base32 character: "$1"',
    algoDesteklenmiyor: "Unsupported algorithm: $1",
    haneDesteklenmiyor: "Unsupported digit count: $1",
    periyotGecersiz: "Invalid period: $1",
    uriOnek: "The link must start with otpauth://",
    uriCozulemedi: "The link could not be parsed.",
    turDesteklenmiyor: "Unsupported type: $1",
    secretYok: "The link has no secret parameter.",
    parolaBos: "The password cannot be empty.",
    veriBozuk: "The encrypted data is corrupt.",
    parolaYanlis: "Wrong password, or the data is corrupt.",
    parolaKisa: "The password must be at least 6 characters.",
    kilitZatenAcik: "A password has already been set.",
    kilitYok: "No password has been set yet.",
    hesapYok: "Account not found.",
    yedekParolaKisa: "The backup password must be at least 6 characters.",
    yedekDegil: "This file is not an exte backup.",
    yedekBozuk: "The backup file is incomplete or corrupt.",
    yedekBicim: "The backup content is not in the expected format.",
    satirHatasi: "line $1: $2",
    gocOnek: "The link must start with otpauth-migration://",
    gocDataYok: "The link has no data parameter.",
    gocHesapYok: "No accounts found in the transfer link.",
    protobufBitti: "The transfer data ended unexpectedly.",
    protobufUzun: "The transfer data is malformed (varint too long).",
    protobufTasma: "The transfer data is malformed (length overflow).",
    protobufTur: "Unsupported field type in the transfer data: $1",
    jsqrYok: "jsQR failed to load (vendor/jsQR.js is missing).",
    yakalanamiyor:
      "This page cannot be captured (chrome:// pages, the Web Store and the PDF viewer are blocked). " +
      'Save the QR as an image and use "Read from image".',
    goruntuAlinamadi: "The screenshot could not be taken.",

    /* --- popup --- */
    uzantiAdi: "exte — Authenticator",
    ara: "Search…",
    araAria: "Search accounts",
    hesapEkle: "Add account",
    ayarlarAc: "Settings and backup",
    kilitli: "Locked",
    kilitIpucu: "Enter your password to see your accounts.",
    parola: "Password",
    kilidiAc: "Unlock",
    kilitle: "Lock",
    kilitlendi: "Locked.",
    kurulumBaslik: "Set your password",
    kurulumIpucu:
      "exte keeps your accounts encrypted with this password and asks for it every time you open the extension.",
    kurulumUyari:
      "<strong>There is no recovery.</strong> Nobody — not even we — can reset this password. " +
      "If you forget it, your accounts are gone for good, so pick something you will remember and take a backup.",
    parolaOlustur: "Set password and continue",
    hesaplar: "Accounts",
    hesapYokMesaj: "No accounts yet.",
    ilkHesabiEkle: "Add your first account",
    eklemeYontemi: "Add method",
    sekmeQr: "QR",
    sekmeBaglanti: "Link",
    sekmeElle: "Manual",
    qrIpucu: "Scan the QR code while it is visible on screen, or read it from an image file.",
    qrEkrandanTara: "Scan from screen",
    qrResimdenOku: "Read from image",
    qrPanoIpucu: "You can also paste a QR image into this window with Ctrl+V.",
    baglantiEtiket: "otpauth:// link",
    ekle: "Add",
    hesapAdi: "Account name",
    servis: "Service (optional)",
    gizliAnahtar: "Secret key (Base32)",
    tur: "Type",
    totpSecenek: "TOTP (time-based)",
    hotpSecenek: "HOTP (counter-based)",
    algoritma: "Algorithm",
    hane: "Digits",
    periyot: "Period (s)",
    listeyeDon: "← Back to list",
    kodKopyalandi: "Code copied",
    kopyalanamadi: "Could not copy",
    hesapSilindi: "Account deleted",
    silOnay: 'Delete "$1"?\n\nIf you have no backup, you may lose access to this account.',
    silAria: "Delete $1",
    kopyalaAria: "Copy the code for $1",
    sonrakiKod: "Next code (increment counter)",
    sonrakiKodAria: "Generate the next code for $1",
    hataliAnahtar: "invalid key",
    hesapEklendi: "$1 account(s) added",
    hesapEklendiAtlandi: "$1 account(s) added, $2 already existed",
    qrBulunamadi: "No QR code found. Is the whole code visible on screen?",
    parcaUyari: "This is part $1 of a $2-part transfer — scan the remaining ones too",
    ekranTaraniyor: "Scanning the screen…",

    /* --- ayarlar sayfası --- */
    ayarlarBaslik: "exte — Settings and backup",
    yukleniyor: "Loading…",
    icerigeAtla: "Skip to content",
    ayarBolumleri: "Settings sections",
    sekmeHesaplar: "Accounts",
    sekmeYedekleme: "Backup and import",
    sekmeGuvenlik: "Security",
    sekmeGorunum: "Appearance",
    ozet: "$1 account(s) · encrypted with your password",
    kilitliOzet: "Locked — enter your password to continue.",
    kurulumOzet: "Set a password to start using exte.",
    disaAktar: "Export",
    yedekParolasi: "Backup password (at least 6 characters)",
    yedekParolaIpucu: "Encrypts the backup file",
    sifreliIndir: "Download encrypted JSON",
    sifresizIndir: "Download unencrypted .txt",
    txtUyari:
      "<strong>The .txt file is not encrypted</strong> — anyone who opens it can read your secret keys. " +
      "Use it only to move accounts to another app, then delete it.",
    txtOnay: "This file is NOT ENCRYPTED — the secret keys are written in plain text.\n\nContinue?",
    iceAktar: "Import",
    iceAktarIpucu:
      "An exte backup (.json) or an <code>otpauth://</code> list (.txt). Existing accounts are kept and duplicates are skipped.",
    yedekParolasiIce: "Backup password (for encrypted JSON)",
    dosyaSec: "Choose file…",
    gocBaslik: "Import from Google Authenticator",
    gocIpucu:
      "On your phone open Google Authenticator → <em>Transfer accounts</em> → <em>Export accounts</em>, " +
      "take a screenshot of the QR code and load it here. With many accounts Google produces several QR codes; load them one by one.",
    gocResimSec: "Choose QR image…",
    gocBaglantiEtiket: "…or paste the <code>otpauth-migration://</code> link",
    gocBaglantidanAktar: "Import from link",
    qrOkunuyor: "Reading the QR code…",
    qrResimdeYok: "No QR code found in the image.",
    parolaKilidi: "Password",
    kilitAciklama:
      "Your secret keys are stored encrypted with your password (AES-256-GCM). " +
      "The password itself is never stored, so it cannot be recovered — keep a backup.",
    yeniParola: "New password (at least 6 characters)",
    parolaTekrar: "Password (again)",
    kilitUyari: "If you forget your password your accounts cannot be recovered — take a backup first.",
    mevcutParola: "Current password",
    parolaDegistirBaslik: "Change password",
    parolaDegistirDugme: "Change password",
    parolaDegistirildi: "Password changed. Your accounts were re-encrypted with the new one.",
    parolalarEslesmiyor: "The passwords do not match.",
    kilitKuruldu: "Password set, your accounts are now encrypted.",
    otomatikKilit: "Ask for the password",
    otoAcilis: "Every time exte is opened (recommended)",
    otoKapali: "Once per browser session",
    otoDk: "After $1 minutes idle",
    otoSaat: "After 1 hour idle",
    otoOzel: "After a period I choose…",
    otoOzelSecili: "After $1 idle (my own period)",
    ozelSure: "Do not ask again for",
    ozelBirim: "Unit",
    birimDk: "minutes",
    birimSaat: "hours",
    birimGun: "days",
    kaydet: "Save",
    sureDk: "$1 minute(s)",
    sureSaat: "$1 hour(s)",
    sureGun: "$1 day(s)",
    otoSureGecersiz: "Enter a whole period between 1 minute and $1 days.",
    otoOzelIpucu:
      "The countdown restarts every time you use exte, so it only locks after you have been away for the whole period.",
    otoGuncellendi: "Auto-lock updated.",
    otoOzelKaydedildi: "Saved — the password will not be asked again for $1 of use.",
    gorunum: "Appearance",
    tema: "Theme",
    temaAuto: "Follow system setting",
    temaAcik: "Light",
    temaKoyu: "Dark",
    dil: "Language",
    dilAuto: "Follow browser language",
    dilEn: "English",
    dilTr: "Türkçe",
    tabloServis: "Service",
    tabloHesap: "Account",
    tabloTur: "Type",
    sil: "Delete",
    kayitliHesapYok: "No saved accounts.",
    disaAktarilacakYok: "There are no accounts to export.",
    dosyadaHesapYok: "No accounts found in the file.",
    sifreliIcinParola: "Enter the password for the encrypted backup.",
    satirOkunamadi: "$1 line(s) could not be read",
    sifreliIndirildi: "$1 account(s) downloaded, encrypted.",
    sifresizIndirildi: "$1 account(s) downloaded as unencrypted .txt — keep the file safe.",
    iceAktarildi: "$1 account(s) added$2.",
    iceAktarildiAtlanan: ", $1 of them already existed",
    gocParca: " ($1-part transfer, part $2 — load the remaining ones too)",
  },

  tr: {
    /* --- çekirdek hatalar --- */
    gizliBos: "Gizli anahtar boş.",
    gizliKisa: "Gizli anahtar çok kısa.",
    base32Gecersiz: 'Geçersiz Base32 karakteri: "$1"',
    algoDesteklenmiyor: "Desteklenmeyen algoritma: $1",
    haneDesteklenmiyor: "Desteklenmeyen hane sayısı: $1",
    periyotGecersiz: "Geçersiz periyot: $1",
    uriOnek: "Bağlantı otpauth:// ile başlamalı.",
    uriCozulemedi: "Bağlantı çözümlenemedi.",
    turDesteklenmiyor: "Desteklenmeyen tür: $1",
    secretYok: "Bağlantıda secret parametresi yok.",
    parolaBos: "Parola boş olamaz.",
    veriBozuk: "Şifreli veri bozuk.",
    parolaYanlis: "Parola yanlış ya da veri bozuk.",
    parolaKisa: "Parola en az 6 karakter olmalı.",
    kilitZatenAcik: "Parola zaten belirlenmiş.",
    kilitYok: "Henüz parola belirlenmemiş.",
    hesapYok: "Hesap bulunamadı.",
    yedekParolaKisa: "Yedek parolası en az 6 karakter olmalı.",
    yedekDegil: "Bu dosya bir exte yedeği değil.",
    yedekBozuk: "Yedek dosyası eksik ya da bozuk.",
    yedekBicim: "Yedek içeriği beklenen biçimde değil.",
    satirHatasi: "$1. satır: $2",
    gocOnek: "Bağlantı otpauth-migration:// ile başlamalı.",
    gocDataYok: "Bağlantıda data parametresi yok.",
    gocHesapYok: "Aktarım bağlantısında hesap bulunamadı.",
    protobufBitti: "Aktarım verisi beklenmedik şekilde bitti.",
    protobufUzun: "Aktarım verisi bozuk (varint çok uzun).",
    protobufTasma: "Aktarım verisi bozuk (uzunluk taşıyor).",
    protobufTur: "Aktarım verisinde desteklenmeyen alan türü: $1",
    jsqrYok: "jsQR yüklenmedi (vendor/jsQR.js eksik).",
    yakalanamiyor:
      "Bu sayfa yakalanamıyor (chrome:// sayfaları, Web Store ve PDF görüntüleyici kapalıdır). " +
      'QR\'ı resim olarak kaydedip "Resimden oku" ile deneyin.',
    goruntuAlinamadi: "Ekran görüntüsü alınamadı.",

    /* --- popup --- */
    uzantiAdi: "exte — Kimlik Doğrulayıcı",
    ara: "Ara…",
    araAria: "Hesaplarda ara",
    hesapEkle: "Hesap ekle",
    ayarlarAc: "Ayarlar ve yedekleme",
    kilitli: "Kilitli",
    kilitIpucu: "Hesapları görmek için parolanızı girin.",
    parola: "Parola",
    kilidiAc: "Kilidi aç",
    kilitle: "Kilitle",
    kilitlendi: "Kilitlendi.",
    kurulumBaslik: "Parolanızı belirleyin",
    kurulumIpucu:
      "exte hesaplarınızı bu parolayla şifreli tutar ve uzantıyı her açtığınızda parolayı sorar.",
    kurulumUyari:
      "<strong>Kurtarma yoktur.</strong> Bu parolayı kimse — biz de dahil — sıfırlayamaz. " +
      "Unutursanız hesaplarınıza bir daha erişemezsiniz; hatırlayacağınız bir parola seçin ve yedek alın.",
    parolaOlustur: "Parolayı belirle ve devam et",
    hesaplar: "Hesaplar",
    hesapYokMesaj: "Henüz hesap yok.",
    ilkHesabiEkle: "İlk hesabı ekle",
    eklemeYontemi: "Ekleme yöntemi",
    sekmeQr: "QR",
    sekmeBaglanti: "Bağlantı",
    sekmeElle: "Elle",
    qrIpucu: "QR kodu ekranda görünür durumdayken tarayın; ya da resim dosyasından okuyun.",
    qrEkrandanTara: "Ekrandan tara",
    qrResimdenOku: "Resimden oku",
    qrPanoIpucu: "QR resmini bu pencereye Ctrl+V ile de yapıştırabilirsiniz.",
    baglantiEtiket: "otpauth:// bağlantısı",
    ekle: "Ekle",
    hesapAdi: "Hesap adı",
    servis: "Servis (isteğe bağlı)",
    gizliAnahtar: "Gizli anahtar (Base32)",
    tur: "Tür",
    totpSecenek: "TOTP (süreli)",
    hotpSecenek: "HOTP (sayaç)",
    algoritma: "Algoritma",
    hane: "Hane",
    periyot: "Periyot (sn)",
    listeyeDon: "← Listeye dön",
    kodKopyalandi: "Kod kopyalandı",
    kopyalanamadi: "Kopyalanamadı",
    hesapSilindi: "Hesap silindi",
    silOnay: '"$1" silinsin mi?\n\nYedeğiniz yoksa bu hesaba erişiminizi kaybedebilirsiniz.',
    silAria: "$1 hesabını sil",
    kopyalaAria: "$1 kodunu kopyala",
    sonrakiKod: "Sonraki kod (sayacı artır)",
    sonrakiKodAria: "$1 için sonraki kodu üret",
    hataliAnahtar: "hatalı anahtar",
    hesapEklendi: "$1 hesap eklendi",
    hesapEklendiAtlandi: "$1 hesap eklendi, $2 zaten vardı",
    qrBulunamadi: "QR kodu bulunamadı. Kodun tamamı ekranda görünüyor mu?",
    parcaUyari: "Bu $2 parçalı aktarımın $1. parçası — diğerlerini de tarayın",
    ekranTaraniyor: "Ekran taranıyor…",

    /* --- ayarlar sayfası --- */
    ayarlarBaslik: "exte — Ayarlar ve yedekleme",
    yukleniyor: "Yükleniyor…",
    icerigeAtla: "İçeriğe atla",
    ayarBolumleri: "Ayar bölümleri",
    sekmeHesaplar: "Hesaplar",
    sekmeYedekleme: "Yedekleme ve aktarım",
    sekmeGuvenlik: "Güvenlik",
    sekmeGorunum: "Görünüm",
    ozet: "$1 hesap · parolanızla şifreli",
    kilitliOzet: "Kilitli — devam etmek için parolanızı girin.",
    kurulumOzet: "exte'yi kullanmaya başlamak için bir parola belirleyin.",
    disaAktar: "Dışa aktar",
    yedekParolasi: "Yedek parolası (en az 6 karakter)",
    yedekParolaIpucu: "Yedek dosyasını şifreler",
    sifreliIndir: "Şifreli JSON indir",
    sifresizIndir: "Şifresiz .txt indir",
    txtUyari:
      "<strong>.txt şifresizdir</strong> — dosyayı açan herkes gizli anahtarlarınızı görür. " +
      "Yalnızca başka bir uygulamaya taşımak için kullanın, sonra silin.",
    txtOnay: "Bu dosya ŞİFRESİZDİR — gizli anahtarlar açık metin olarak yazılır.\n\nDevam edilsin mi?",
    iceAktar: "İçe aktar",
    iceAktarIpucu:
      "exte yedeği (.json) veya <code>otpauth://</code> listesi (.txt). Mevcut hesaplar korunur, tekrarlananlar atlanır.",
    yedekParolasiIce: "Yedek parolası (şifreli JSON için)",
    dosyaSec: "Dosya seç…",
    gocBaslik: "Google Authenticator'dan aktar",
    gocIpucu:
      "Telefonda Google Authenticator → <em>Hesapları aktar</em> → <em>Hesapları dışa aktar</em> ile " +
      "çıkan QR'ın ekran görüntüsünü alın, buradan yükleyin. Çok hesapta birden fazla QR çıkar; hepsini sırayla yükleyin.",
    gocResimSec: "QR resmi seç…",
    gocBaglantiEtiket: "…veya <code>otpauth-migration://</code> bağlantısını yapıştırın",
    gocBaglantidanAktar: "Bağlantıdan aktar",
    qrOkunuyor: "QR okunuyor…",
    qrResimdeYok: "Resimde QR kodu bulunamadı.",
    parolaKilidi: "Parola",
    kilitAciklama:
      "Gizli anahtarlar parolanızla şifreli saklanıyor (AES-256-GCM). " +
      "Parolanın kendisi hiçbir yerde tutulmaz, bu yüzden kurtarılamaz — yedeğinizi alın.",
    yeniParola: "Yeni parola (en az 6 karakter)",
    parolaTekrar: "Parola (tekrar)",
    kilitUyari: "Parolanızı unutursanız hesaplar geri alınamaz — önce yedek alın.",
    mevcutParola: "Mevcut parola",
    parolaDegistirBaslik: "Parolayı değiştir",
    parolaDegistirDugme: "Parolayı değiştir",
    parolaDegistirildi: "Parola değiştirildi. Hesaplar yeni parolayla yeniden şifrelendi.",
    parolalarEslesmiyor: "Parolalar eşleşmiyor.",
    kilitKuruldu: "Parola belirlendi, hesaplar şifrelendi.",
    otomatikKilit: "Parola sorulsun",
    otoAcilis: "exte her açıldığında (önerilen)",
    otoKapali: "Tarayıcı oturumunda bir kez",
    otoDk: "$1 dakika işlem yapılmazsa",
    otoSaat: "1 saat işlem yapılmazsa",
    otoOzel: "Belirlediğim süre sonra…",
    otoOzelSecili: "$1 işlem yapılmazsa (kendi sürem)",
    ozelSure: "Şu süre boyunca tekrar sorma",
    ozelBirim: "Birim",
    birimDk: "dakika",
    birimSaat: "saat",
    birimGun: "gün",
    kaydet: "Kaydet",
    sureDk: "$1 dakika",
    sureSaat: "$1 saat",
    sureGun: "$1 gün",
    otoSureGecersiz: "1 dakika ile $1 gün arasında tam bir süre girin.",
    otoOzelIpucu:
      "Süre exte'yi her kullandığınızda baştan başlar; yani kilit ancak bu süre boyunca hiç kullanmadığınızda devreye girer.",
    otoGuncellendi: "Otomatik kilitlenme güncellendi.",
    otoOzelKaydedildi: "Kaydedildi — parola $1 boyunca tekrar sorulmayacak.",
    gorunum: "Görünüm",
    tema: "Tema",
    temaAuto: "Sistem ayarını izle",
    temaAcik: "Açık",
    temaKoyu: "Koyu",
    dil: "Dil",
    dilAuto: "Tarayıcı dilini izle",
    dilEn: "English",
    dilTr: "Türkçe",
    tabloServis: "Servis",
    tabloHesap: "Hesap",
    tabloTur: "Tür",
    sil: "Sil",
    kayitliHesapYok: "Kayıtlı hesap yok.",
    disaAktarilacakYok: "Dışa aktarılacak hesap yok.",
    dosyadaHesapYok: "Dosyada hesap bulunamadı.",
    sifreliIcinParola: "Şifreli yedek için parola girin.",
    satirOkunamadi: "$1 satır okunamadı",
    sifreliIndirildi: "$1 hesap şifreli olarak indirildi.",
    sifresizIndirildi: "$1 hesap şifresiz .txt olarak indirildi — dosyayı güvenle saklayın.",
    iceAktarildi: "$1 hesap eklendi$2.",
    iceAktarildiAtlanan: ", $1 tanesi zaten vardı",
    gocParca: " ($1 parçalı aktarımın $2. parçası — kalanları da yükleyin)",
  },
};

let DIL = "en";

/** Etkin dili ayarlar. `kod`: "en" | "tr" | "auto" (tarayıcı diline bakar). */
export function diliAyarla(kod) {
  if (kod === "auto" || !kod) {
    const tarayici = globalThis.navigator?.language || "en";
    DIL = tarayici.toLowerCase().startsWith("tr") ? "tr" : "en";
  } else {
    DIL = METINLER[kod] ? kod : "en";
  }
  return DIL;
}

export const etkinDil = () => DIL;

/** Anahtarı etkin dilde döndürür; `$1`, `$2`… yer tutucularını sırayla değiştirir. */
export function t(anahtar, ...ikame) {
  const metin = METINLER[DIL]?.[anahtar] ?? METINLER.en[anahtar] ?? anahtar;
  return ikame.length ? metin.replace(/\$(\d)/g, (_, n) => String(ikame[n - 1] ?? "")) : metin;
}
